/**
 * THE CANONICAL RAGAB CATEGORY TAXONOMY (§catalog import).
 *
 * Transcribed from the owner's brief. Two levels only — see types.ts for why the brief's
 * third indent level (the bullets) is the PRODUCT level and becomes `keywordsAr` here,
 * never `categories` rows.
 *
 * ───────────────────────────────────────────────────────────────────────────────────────
 * REUSED IDS: the 8 categories already in db/seed.ts map cleanly onto 8 of these parents,
 * so their `id` and `slug` are REUSED rather than replaced. That keeps every existing
 * `promotion_categories` row, integration-test fixture (`cat_dairy`, `cat_groceries`,
 * `cat_beverages`) and e2e spec pointing at a live row. Reused: cat_beverages, cat_dairy,
 * cat_bakery, cat_groceries, cat_snacks, cat_cleaning, cat_care, cat_fresh.
 *
 * SECTION 25 (منتجات الكاشير) IS DELIBERATELY NOT A CATEGORY. The owner's own
 * organizational note 6 says: "منتجات الكاشير ليست Category غذائية — يمكن التعامل معها كـ
 * Placement = Checkout بدل إنشاء Categories كثيرة". Every product it lists (علكة، شوكولاتة
 * صغيرة، مناديل جيب، بطاريات، معقم يدين) already has a primary home in sections 12, 17 and
 * 23, and note 7 requires exactly one primary home per product. So checkout is carried as
 * the `كاشير` facet tag (see facets.ts FACET_TAGS) instead of a 25th parent — nothing is
 * lost, and no product is duplicated. Adding it back is a single block here if the owner
 * prefers it as a browsable department.
 *
 * SLUGS: children are ALWAYS `<parentSlug>-<leaf>`. `categories_slug_uidx` is
 * (store_id, slug) — store-scoped, not parent-scoped — and `asciiSlug()` of an Arabic-only
 * name is the empty string, so prefixed English slugs are what make all ~112 unique by
 * construction. sortOrder: parents = brief number × 100, children = brief decimal × 10.
 */
import type { CategoryDef } from './types';
import { CANNED_TOKENS, FREEZER_TOKENS, PROCESSED_PRODUCE_TOKENS } from './facets';

/** Shorthand: ambient/chilled leaves must never absorb a frozen product (owner rule 4). */
const NOT_FROZEN = [...FREEZER_TOKENS];
/** Fresh-produce leaves reject frozen, canned, dried and juiced forms (owner rule 5). */
const FRESH_ONLY = [...PROCESSED_PRODUCE_TOKENS];

export const TAXONOMY: readonly CategoryDef[] = [
  /* ── 1. المشروبات ──────────────────────────────────────────────────────────────── */
  {
    id: 'cat_beverages', // REUSED from seed.ts
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'beverages',
    nameAr: 'المشروبات',
    nameEn: 'Beverages',
    iconName: 'cup-soda',
    colorTheme: 'rose',
    sortOrder: 100,
    // Un-featured: 0 real products until a grocery source is imported — see cat_med etc.
    // below, which now carry the store's actual featured content (chefaa import).
    featured: false,
    children: [
      {
        id: 'cat_bev_water',
        slug: 'beverages-water',
        nameAr: 'المياه',
        nameEn: 'Water',
        sortOrder: 10,
        keywordsAr: ['مياه معدنية', 'مياه شرب', 'عبوات مياه صغيرة', 'عبوات مياه متوسطة', 'عبوات مياه كبيرة', 'جالونات مياه', 'عبوات مياه غازية'],
        keywordsEn: ['mineral water', 'drinking water', 'still water', 'water gallon', 'sparkling water'],
        matchAlso: ['مياه', 'مياه معدنيه', 'water'],
        // Tokens are written PRE-FOLDED (see normalize.ts fold): مياة folds to مياه, so one
        // entry covers both spellings. ماء is omitted — it folds to the 2-char ما, too loose.
        requireAny: ['مياه', 'water'],
        forbidAny: [...NOT_FROZEN, 'عصير', 'juice', 'ورد', 'زهر'],
      },
      {
        id: 'cat_bev_carbonated',
        slug: 'beverages-carbonated',
        nameAr: 'المشروبات الغازية',
        nameEn: 'Carbonated Drinks',
        sortOrder: 20,
        keywordsAr: ['كولا', 'مشروبات غازية بنكهة الليمون', 'مشروبات غازية بنكهة البرتقال', 'مشروبات غازية بنكهة التفاح', 'مشروبات غازية بنكهة التوت', 'مشروبات غازية دايت', 'مشروبات غازية بدون سكر'],
        keywordsEn: ['cola', 'soft drink', 'carbonated', 'soda', 'diet cola', 'zero sugar'],
        matchAlso: ['غازيه', 'صودا', 'كولا', 'soda', 'cola', 'carbonated'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_bev_juices',
        slug: 'beverages-juices',
        nameAr: 'العصائر والمشروبات الباردة',
        nameEn: 'Juices & Cold Drinks',
        sortOrder: 30,
        keywordsAr: ['عصائر جاهزة', 'نكتار', 'عصائر طبيعية مبردة', 'عصائر بودرة', 'مشروبات فواكه', 'مشروبات مانجو', 'مشروبات برتقال', 'مشروبات تفاح', 'مشروبات كوكتيل'],
        keywordsEn: ['juice', 'nectar', 'fruit drink', 'powdered drink', 'mango drink', 'orange juice', 'cocktail'],
        matchAlso: ['عصير', 'عصاير', 'نكتار', 'juice', 'nectar'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_bev_energy',
        slug: 'beverages-energy-sports',
        nameAr: 'مشروبات الطاقة والرياضة',
        nameEn: 'Energy & Sports Drinks',
        sortOrder: 40,
        keywordsAr: ['مشروبات طاقة', 'مشروبات رياضية', 'مشروبات فيتامينات', 'مشروبات وظيفية'],
        keywordsEn: ['energy drink', 'sports drink', 'vitamin drink', 'functional drink'],
        matchAlso: ['طاقه', 'energy drink'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_bev_hot',
        slug: 'beverages-hot-drinks',
        nameAr: 'المشروبات الساخنة',
        nameEn: 'Hot Beverages',
        sortOrder: 50,
        keywordsAr: ['شاي', 'شاي أخضر', 'شاي نكهات', 'قهوة سريعة التحضير', 'قهوة تركية', 'قهوة مطحونة', 'قهوة سادة', 'قهوة سريعة الذوبان', 'كابتشينو', '3 في 1', 'هوت شوكليت', 'مشروبات أعشاب'],
        keywordsEn: ['tea', 'green tea', 'instant coffee', 'turkish coffee', 'ground coffee', 'cappuccino', '3 in 1', 'hot chocolate', 'herbal tea', 'nescafe'],
        matchAlso: ['شاي', 'قهوه', 'بن', 'نسكافيه', 'كاكاو', 'tea', 'coffee', 'cocoa'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 2. الألبان ومنتجات الثلاجة ─────────────────────────────────────────────────── */
  {
    id: 'cat_dairy', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'dairy',
    nameAr: 'الألبان ومنتجات الثلاجة',
    nameEn: 'Dairy & Chilled',
    iconName: 'milk',
    colorTheme: 'blue',
    sortOrder: 200,
    featured: false,
    children: [
      {
        id: 'cat_dairy_milk',
        slug: 'dairy-milk',
        nameAr: 'اللبن',
        nameEn: 'Milk',
        sortOrder: 10,
        keywordsAr: ['لبن كامل الدسم', 'لبن نصف دسم', 'لبن خالي الدسم', 'لبن طويل الأجل', 'لبن مبستر', 'لبن منكّه'],
        keywordsEn: ['full cream milk', 'low fat milk', 'skimmed milk', 'long life milk', 'uht milk', 'flavoured milk'],
        matchAlso: ['لبن', 'حليب', 'milk'],
        // NOT vetoing بودرة: the brief has no powdered-milk bullet, and rules.ts deliberately
        // files dairy/powdered-milk here (tagged 'لبن بودرة') since customers look for it
        // under الألبان. A veto here would silently drop those 19 products.
        //
        // DOES veto 'رايب': "لبن رايب"/"حليب رايب" is a fermented drinking-yogurt product
        // (rules.ts routes dairy/yogurt-drinks-rayeb to cat_dairy_yoghurt), not plain milk —
        // but it bare-matches milk's own generic 'لبن'/'حليب' matchAlso tokens and, being a
        // same-parent sibling, was winning the sibling-refinement check on that alone and
        // silently overriding the source-path rule's correct target.
        forbidAny: [...NOT_FROZEN, 'رايب'],
      },
      {
        id: 'cat_dairy_yoghurt',
        slug: 'dairy-yoghurt',
        nameAr: 'الزبادي',
        nameEn: 'Yoghurt',
        sortOrder: 20,
        keywordsAr: ['زبادي طبيعي', 'زبادي فواكه', 'زبادي يوناني', 'زبادي لايت', 'زبادي للأطفال', 'زبادي للشرب'],
        keywordsEn: ['yoghurt', 'yogurt', 'greek yoghurt', 'fruit yoghurt', 'drinking yoghurt'],
        matchAlso: ['زبادي', 'روب', 'yoghurt', 'yogurt'],
        requireAny: ['زبادي', 'روب', 'yoghurt', 'yogurt'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_dairy_cheese',
        slug: 'dairy-cheese',
        nameAr: 'الجبن',
        nameEn: 'Cheese',
        sortOrder: 30,
        keywordsAr: ['جبنة بيضاء', 'جبنة قريش', 'جبنة دمياطي', 'جبنة فيتا', 'جبنة مثلثات', 'جبنة قابلة للدهن', 'جبنة شيدر', 'جبنة رومي', 'جبنة موزاريلا', 'جبنة تركي', 'جبنة شرائح', 'جبنة مطبوخة'],
        keywordsEn: ['white cheese', 'feta', 'cream cheese', 'spreadable cheese', 'cheddar', 'roumy', 'mozzarella', 'cheese slices', 'processed cheese'],
        matchAlso: ['جبن', 'cheese'],
        requireAny: ['جبن', 'cheese'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_dairy_butter',
        slug: 'dairy-butter',
        nameAr: 'الزبدة والسمن المبرد',
        nameEn: 'Butter & Chilled Fats',
        sortOrder: 40,
        keywordsAr: ['زبدة', 'زبدة مملحة', 'زبدة غير مملحة', 'مارجرين'],
        keywordsEn: ['butter', 'salted butter', 'unsalted butter', 'margarine'],
        matchAlso: ['زبده', 'سمنه', 'مارجرين', 'butter', 'margarine'],
        forbidAny: [...NOT_FROZEN, 'فول سوداني', 'peanut'],
      },
      {
        id: 'cat_dairy_cream',
        slug: 'dairy-cream',
        nameAr: 'الكريمة والمنتجات المبردة',
        nameEn: 'Cream & Chilled Products',
        sortOrder: 50,
        // NOT 'لبن رايب'/'laban rayeb': rules.ts already routes dairy/yogurt-drinks-rayeb to
        // cat_dairy_yoghurt (review:true, straddles زبادي للشرب). Keeping the phrase here as a
        // keyword let the same-parent sibling refinement hijack every one of those products
        // straight back out of Yoghurt and into Cream on an exact keyword match — the opposite
        // of what the source-path rule decided. Cream's own signal (كريمة/قشطة/كفير) is enough.
        keywordsAr: ['كريمة طبخ', 'كريمة خفق', 'كريمة حلويات', 'قشطة', 'كفير', 'منتجات ألبان مبردة متنوعة'],
        keywordsEn: ['cooking cream', 'whipping cream', 'clotted cream', 'kefir', 'chilled dairy'],
        matchAlso: ['كريمه', 'قشطه', 'لبنه', 'cream', 'labneh'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_dairy_eggs',
        slug: 'dairy-eggs',
        nameAr: 'البيض',
        nameEn: 'Eggs',
        sortOrder: 60,
        keywordsAr: ['بيض أبيض', 'بيض أحمر', 'بيض بلدي', 'بيض عضوي', 'عبوات بيض بأحجام مختلفة'],
        keywordsEn: ['white eggs', 'brown eggs', 'red eggs', 'organic eggs', 'eggs'],
        matchAlso: ['بيض', 'egg'],
        requireAny: ['بيض', 'egg'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 3. الجبن واللحوم المبردة ───────────────────────────────────────────────────── */
  {
    id: 'cat_deli',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'chilled-deli',
    nameAr: 'اللحوم المبردة والدليكاتيسن',
    nameEn: 'Chilled Meats & Deli',
    iconName: 'ham',
    colorTheme: 'rose',
    sortOrder: 300,
    children: [
      {
        id: 'cat_deli_processed',
        slug: 'chilled-deli-processed-meats',
        nameAr: 'اللحوم المصنعة',
        nameEn: 'Processed Meats',
        sortOrder: 10,
        keywordsAr: ['لانشون', 'بسطرمة', 'روزبيف', 'تركي مدخن', 'هوت دوج', 'سجق مبرد', 'سلامي'],
        keywordsEn: ['luncheon', 'pastrami', 'roast beef', 'smoked turkey', 'hot dog', 'sausage', 'salami'],
        matchAlso: ['لانشون', 'بسطرمه', 'سلامي', 'سجق', 'luncheon', 'pastrami', 'salami', 'sausage'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_deli_ready',
        slug: 'chilled-deli-ready-meats',
        nameAr: 'اللحوم المبردة الجاهزة',
        nameEn: 'Chilled Ready Meats',
        sortOrder: 20,
        keywordsAr: ['برجر مبرد', 'كفتة مبردة', 'كباب مبرد', 'شاورما جاهزة', 'لحوم متبلة'],
        keywordsEn: ['chilled burger', 'kofta', 'kebab', 'shawarma', 'marinated meat'],
        matchAlso: ['شاورما', 'متبل', 'برجر مبرد', 'marinated', 'shawarma'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_deli_salads',
        slug: 'chilled-deli-salads',
        nameAr: 'سلطات ومقبلات مبردة',
        nameEn: 'Chilled Salads & Dips',
        sortOrder: 30,
        keywordsAr: ['حمص', 'بابا غنوج', 'متبل', 'سلطة كول سلو', 'مخللات مبردة', 'سلطات جاهزة'],
        keywordsEn: ['hummus', 'baba ghanoush', 'mutabal', 'coleslaw', 'pickles', 'ready salad'],
        matchAlso: ['حمص', 'بابا غنوج', 'كول سلو', 'hummus', 'coleslaw'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 4. المخبوزات والخبز ────────────────────────────────────────────────────────── */
  {
    id: 'cat_bakery', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'bakery',
    nameAr: 'المخبوزات والخبز',
    nameEn: 'Bakery & Bread',
    iconName: 'croissant',
    colorTheme: 'orange',
    sortOrder: 400,
    featured: false,
    children: [
      {
        id: 'cat_bakery_bread',
        slug: 'bakery-bread',
        nameAr: 'الخبز',
        nameEn: 'Bread',
        sortOrder: 10,
        keywordsAr: ['خبز بلدي', 'خبز شامي', 'عيش فينو', 'عيش توست', 'خبز برجر', 'خبز هوت دوج', 'خبز أسمر', 'خبز حبوب كاملة'],
        keywordsEn: ['bread', 'pita bread', 'toast bread', 'burger buns', 'hot dog buns', 'brown bread', 'wholemeal bread'],
        matchAlso: ['خبز', 'عيش', 'توست', 'bread', 'toast'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_bakery_pastries',
        slug: 'bakery-pastries',
        nameAr: 'المخبوزات الجاهزة',
        nameEn: 'Ready Baked Goods',
        sortOrder: 20,
        keywordsAr: ['كرواسون', 'دونات', 'مافن', 'باتيه', 'فطائر', 'معجنات', 'مخبوزات محشوة'],
        keywordsEn: ['croissant', 'donut', 'muffin', 'pattie', 'pastry', 'filled pastry'],
        matchAlso: ['معجنات', 'فطاير', 'pastry', 'pastries'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_bakery_cakes',
        slug: 'bakery-cakes',
        nameAr: 'الكيك والحلويات المخبوزة',
        nameEn: 'Cakes & Baked Sweets',
        sortOrder: 30,
        keywordsAr: ['كيك سادة', 'كيك شوكولاتة', 'سويس رول', 'قطع كيك', 'كب كيك'],
        keywordsEn: ['cake', 'chocolate cake', 'swiss roll', 'cupcake', 'cake slice'],
        matchAlso: ['كيك', 'cake'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 5. الحبوب والأرز والمكرونة والبقوليات ──────────────────────────────────────── */
  {
    id: 'cat_grains',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'grains-pasta',
    nameAr: 'الحبوب والأرز والمكرونة والبقوليات',
    nameEn: 'Grains, Rice, Pasta & Legumes',
    iconName: 'wheat',
    colorTheme: 'brand',
    sortOrder: 500,
    children: [
      {
        id: 'cat_grains_rice',
        slug: 'grains-pasta-rice',
        nameAr: 'الأرز',
        nameEn: 'Rice',
        sortOrder: 10,
        keywordsAr: ['أرز مصري', 'أرز بسمتي', 'أرز حبة طويلة', 'أرز حبة قصيرة', 'أرز أبيض', 'أرز بني'],
        keywordsEn: ['egyptian rice', 'basmati rice', 'long grain rice', 'short grain rice', 'white rice', 'brown rice'],
        matchAlso: ['ارز', 'rice'],
        requireAny: ['ارز', 'rice'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_grains_pasta',
        slug: 'grains-pasta-pasta',
        nameAr: 'المكرونة',
        nameEn: 'Pasta',
        sortOrder: 20,
        keywordsAr: ['مكرونة سباجيتي', 'مكرونة قلم', 'مكرونة خواتم', 'مكرونة صدف', 'مكرونة فيونكة', 'مكرونة شعرية', 'مكرونة لازانيا', 'مكرونة لسان عصفور'],
        keywordsEn: ['spaghetti', 'penne', 'rings pasta', 'shells pasta', 'bow tie pasta', 'vermicelli', 'lasagna', 'orzo'],
        matchAlso: ['مكرونه', 'معكرونه', 'pasta', 'spaghetti'],
        requireAny: ['مكرونه', 'معكرونه', 'باستا', 'pasta', 'spaghetti', 'noodle'],
        forbidAny: [...NOT_FROZEN, 'سريعه التحضير', 'سريع التحضير', 'instant'],
      },
      {
        id: 'cat_grains_cereals',
        slug: 'grains-pasta-grains',
        nameAr: 'الحبوب',
        nameEn: 'Grains',
        sortOrder: 30,
        keywordsAr: ['قمح', 'فريك', 'برغل', 'شوفان', 'ذرة', 'شعير', 'حبوب إفطار'],
        keywordsEn: ['wheat', 'freekeh', 'bulgur', 'oats', 'corn', 'barley'],
        matchAlso: ['شوفان', 'برغل', 'فريك', 'قمح', 'شعير', 'oats', 'bulgur', 'wheat', 'barley'],
        forbidAny: [...NOT_FROZEN, ...CANNED_TOKENS],
      },
      {
        id: 'cat_grains_legumes',
        slug: 'grains-pasta-legumes',
        nameAr: 'البقوليات',
        nameEn: 'Legumes',
        sortOrder: 40,
        keywordsAr: ['فول جاف', 'عدس أصفر', 'عدس بجبة', 'حمص جاف', 'فاصوليا بيضاء', 'لوبيا', 'بسلة جافة'],
        keywordsEn: ['dry beans', 'yellow lentils', 'brown lentils', 'chickpeas', 'white beans', 'black eyed peas', 'dried peas'],
        matchAlso: ['فول', 'عدس', 'حمص', 'فاصوليا', 'لوبيا', 'بسله', 'lentil', 'beans', 'chickpea'],
        forbidAny: [...NOT_FROZEN, ...CANNED_TOKENS],
      },
    ],
  },

  /* ── 6. الدقيق والسكر والمواد الأساسية للخبز ────────────────────────────────────── */
  {
    id: 'cat_baking',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'baking',
    nameAr: 'الدقيق والسكر ومستلزمات الخبز',
    nameEn: 'Flour, Sugar & Baking',
    iconName: 'cake-slice',
    colorTheme: 'orange',
    sortOrder: 600,
    children: [
      {
        id: 'cat_baking_flour',
        slug: 'baking-flour',
        nameAr: 'الدقيق',
        nameEn: 'Flour',
        sortOrder: 10,
        keywordsAr: ['دقيق فاخر', 'دقيق متعدد الاستخدام', 'دقيق خبز', 'دقيق كامل الحبة', 'دقيق ذرة', 'دقيق أرز'],
        keywordsEn: ['flour', 'all purpose flour', 'bread flour', 'wholemeal flour', 'corn flour', 'rice flour'],
        matchAlso: ['دقيق', 'نشا', 'flour', 'starch'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_baking_sugar',
        slug: 'baking-sugar',
        nameAr: 'السكر',
        nameEn: 'Sugar',
        sortOrder: 20,
        keywordsAr: ['سكر أبيض', 'سكر بودرة', 'سكر بني', 'سكر دايت'],
        keywordsEn: ['white sugar', 'icing sugar', 'powdered sugar', 'brown sugar', 'diet sugar', 'sweetener'],
        matchAlso: ['سكر', 'سكرين', 'sugar', 'sweetener'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_baking_supplies',
        slug: 'baking-supplies',
        nameAr: 'مستلزمات الخَبز',
        nameEn: 'Baking Supplies',
        sortOrder: 30,
        keywordsAr: ['خميرة', 'بيكنج بودر', 'بيكنج صودا', 'فانيليا', 'نشا', 'جيلاتين', 'ألوان طعام', 'منكهات', 'جوز هند', 'كاكاو خام'],
        keywordsEn: ['yeast', 'baking powder', 'baking soda', 'vanilla', 'corn starch', 'gelatin', 'food colouring', 'flavouring', 'coconut', 'cocoa powder'],
        matchAlso: ['خميره', 'بيكنج', 'فانيليا', 'جيلاتين', 'yeast', 'baking powder', 'vanilla', 'gelatin'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 7. الزيوت والسمن والصلصات ──────────────────────────────────────────────────── */
  {
    id: 'cat_oils',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'oils-sauces',
    nameAr: 'الزيوت والسمن والصلصات',
    nameEn: 'Oils, Fats & Sauces',
    iconName: 'droplet',
    colorTheme: 'green',
    sortOrder: 700,
    children: [
      {
        id: 'cat_oils_oil',
        slug: 'oils-sauces-oils',
        nameAr: 'الزيوت',
        nameEn: 'Cooking Oils',
        sortOrder: 10,
        keywordsAr: ['زيت ذرة', 'زيت عباد الشمس', 'زيت كانولا', 'زيت زيتون', 'زيت نباتي', 'زيت خليط'],
        keywordsEn: ['corn oil', 'sunflower oil', 'canola oil', 'olive oil', 'vegetable oil', 'blended oil'],
        matchAlso: ['زيت', 'oil'],
        requireAny: ['زيت', 'oil'],
        forbidAny: [...NOT_FROZEN, 'شعر', 'hair', 'اطفال', 'baby', 'عطر'],
      },
      {
        id: 'cat_oils_ghee',
        slug: 'oils-sauces-ghee',
        nameAr: 'السمن',
        nameEn: 'Ghee & Shortening',
        sortOrder: 20,
        keywordsAr: ['سمن نباتي', 'سمن بلدي', 'سمن بقري', 'سمن جاموسي'],
        keywordsEn: ['vegetable ghee', 'ghee', 'butter ghee', 'shortening'],
        matchAlso: ['سمن', 'سمنه', 'ghee'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_oils_sauces',
        slug: 'oils-sauces-sauces',
        nameAr: 'الصلصات',
        nameEn: 'Sauces & Condiments',
        sortOrder: 30,
        keywordsAr: ['صلصة طماطم', 'كاتشب', 'مايونيز', 'مستردة', 'باربكيو', 'صوص ثوم', 'صوص جبنة', 'صوص حار'],
        keywordsEn: ['tomato sauce', 'ketchup', 'mayonnaise', 'mustard', 'barbecue sauce', 'garlic sauce', 'cheese sauce', 'hot sauce'],
        matchAlso: ['صوص', 'كاتشب', 'مايونيز', 'مستردا', 'صلصه', 'sauce', 'ketchup', 'mayonnaise', 'mustard'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_oils_vinegar',
        slug: 'oils-sauces-vinegar',
        nameAr: 'الخل والمواد السائلة',
        nameEn: 'Vinegar & Liquids',
        sortOrder: 40,
        keywordsAr: ['خل أبيض', 'خل تفاح', 'خل عنب', 'خل بلسمي', 'عصير ليمون', 'دبس رمان'],
        keywordsEn: ['white vinegar', 'apple cider vinegar', 'grape vinegar', 'balsamic vinegar', 'lemon juice', 'pomegranate molasses'],
        matchAlso: ['خل', 'vinegar'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 8. المعلبات والمحفوظات ─────────────────────────────────────────────────────── */
  {
    id: 'cat_canned',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'canned-preserved',
    nameAr: 'المعلبات والمحفوظات',
    nameEn: 'Canned & Preserved',
    iconName: 'archive',
    colorTheme: 'orange',
    sortOrder: 800,
    children: [
      {
        id: 'cat_canned_veg',
        slug: 'canned-preserved-vegetables',
        nameAr: 'الخضروات المعلبة',
        nameEn: 'Canned Vegetables',
        sortOrder: 10,
        keywordsAr: ['ذرة', 'بسلة', 'فاصوليا', 'مشروم', 'خضروات مشكلة', 'خرشوف'],
        keywordsEn: ['canned corn', 'canned peas', 'canned beans', 'mushroom', 'mixed vegetables', 'artichoke'],
        matchAlso: ['ذره', 'بسله', 'مشروم', 'خرشوف', 'corn', 'mushroom', 'artichoke'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_canned_legumes',
        slug: 'canned-preserved-legumes',
        nameAr: 'البقوليات المعلبة',
        nameEn: 'Canned Legumes',
        sortOrder: 20,
        keywordsAr: ['فول مدمس', 'حمص', 'فاصوليا', 'لوبيا', 'عدس'],
        keywordsEn: ['foul medames', 'canned chickpeas', 'canned beans', 'canned lentils'],
        matchAlso: ['فول مدمس', 'حمص', 'foul', 'chickpea'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_canned_fish',
        slug: 'canned-preserved-fish',
        nameAr: 'الأسماك المعلبة',
        nameEn: 'Canned Fish',
        sortOrder: 30,
        keywordsAr: ['تونة', 'سردين', 'ماكريل', 'أنشوجة'],
        keywordsEn: ['tuna', 'sardines', 'mackerel', 'anchovy'],
        matchAlso: ['تونه', 'سردين', 'ماكريل', 'انشوجه', 'tuna', 'sardine', 'mackerel', 'anchovy'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_canned_ready',
        slug: 'canned-preserved-ready',
        nameAr: 'المعلبات والجاهز',
        nameEn: 'Canned & Ready Meals',
        sortOrder: 40,
        keywordsAr: ['صلصة طماطم', 'معجون طماطم', 'شوربة جاهزة', 'لحوم معلبة', 'وجبات معلبة', 'فواكه معلبة'],
        keywordsEn: ['tomato paste', 'canned soup', 'canned meat', 'canned meal', 'canned fruit'],
        matchAlso: ['معجون طماطم', 'صلصه', 'tomato paste'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_canned_jam',
        slug: 'canned-preserved-jam-honey',
        nameAr: 'المربى والعسل',
        nameEn: 'Jam & Honey',
        sortOrder: 50,
        keywordsAr: ['مربى فراولة', 'مربى مشمش', 'مربى تين', 'مربى برتقال', 'عسل نحل', 'عسل أسود', 'زبدة فول سوداني'],
        keywordsEn: ['strawberry jam', 'apricot jam', 'fig jam', 'orange marmalade', 'honey', 'molasses', 'peanut butter'],
        matchAlso: ['مربي', 'عسل', 'زبده فول سوداني', 'jam', 'honey', 'peanut butter'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 9. التوابل والأعشاب والمكونات الجافة ───────────────────────────────────────── */
  {
    id: 'cat_spices',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'spices-herbs',
    nameAr: 'التوابل والأعشاب',
    nameEn: 'Spices & Herbs',
    iconName: 'leaf',
    colorTheme: 'green',
    sortOrder: 900,
    children: [
      {
        id: 'cat_spices_basic',
        slug: 'spices-herbs-essentials',
        nameAr: 'التوابل الأساسية',
        nameEn: 'Essential Spices',
        sortOrder: 10,
        keywordsAr: ['ملح', 'فلفل أسود', 'كمون', 'كزبرة ناشفة', 'قرفة', 'زنجبيل', 'كركم', 'بابريكا', 'شطة', 'حبهان', 'قرنفل'],
        keywordsEn: ['salt', 'black pepper', 'cumin', 'coriander', 'cinnamon', 'ginger', 'turmeric', 'paprika', 'chilli', 'cardamom', 'cloves'],
        matchAlso: ['ملح', 'فلفل', 'كمون', 'كزبره', 'قرفه', 'زنجبيل', 'كركم', 'شطه', 'حبهان', 'قرنفل', 'salt', 'pepper', 'cumin', 'cinnamon'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_spices_blends',
        slug: 'spices-herbs-blends',
        nameAr: 'خلطات التوابل',
        nameEn: 'Spice Blends',
        sortOrder: 20,
        keywordsAr: ['توابل فراخ', 'توابل لحوم', 'توابل أسماك', 'توابل مشويات', 'توابل بطاطس', 'توابل شاورما', 'توابل كبسة', 'توابل أرز'],
        keywordsEn: ['chicken spice', 'meat spice', 'fish spice', 'grill spice', 'potato seasoning', 'shawarma spice', 'kabsa spice', 'rice spice'],
        // 'بهار' (singular) is a very common Egyptian attar-shop synonym for 'توابل' — "بهار
        // كفتة"/"بهار شاورما"/"بهار محاشي" are spice BLENDS, but none of the owner's bullets
        // use that spelling, so without it these blends were staying in 9.1 (basic spices)
        // instead of refining to this sibling leaf. Verified against ~90 real products.
        matchAlso: ['توابل', 'بهار', 'بهارات', 'خلطه', 'spice mix', 'seasoning'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_spices_dried_herbs',
        slug: 'spices-herbs-dried',
        nameAr: 'الأعشاب',
        nameEn: 'Dried Herbs',
        sortOrder: 30,
        keywordsAr: ['نعناع مجفف', 'زعتر', 'روزماري', 'ريحان', 'يانسون', 'كركديه', 'شمر'],
        keywordsEn: ['dried mint', 'thyme', 'rosemary', 'basil', 'anise', 'hibiscus', 'fennel'],
        matchAlso: ['نعناع', 'زعتر', 'روزماري', 'ريحان', 'يانسون', 'كركديه', 'شمر', 'بابونج', 'thyme', 'hibiscus'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 10. الإفطار والحبوب ومنتجات السبريد ────────────────────────────────────────── */
  {
    id: 'cat_breakfast',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'breakfast',
    nameAr: 'الإفطار والسبريد',
    nameEn: 'Breakfast & Spreads',
    iconName: 'egg-fried',
    colorTheme: 'violet',
    sortOrder: 1000,
    children: [
      {
        id: 'cat_breakfast_cereal',
        slug: 'breakfast-cereals',
        nameAr: 'حبوب الإفطار',
        nameEn: 'Breakfast Cereals',
        sortOrder: 10,
        keywordsAr: ['كورن فليكس', 'حبوب شوكولاتة', 'جرانولا', 'موسلي', 'حبوب إفطار بالعسل'],
        keywordsEn: ['corn flakes', 'chocolate cereal', 'granola', 'muesli', 'honey cereal'],
        matchAlso: ['كورن فليكس', 'جرانولا', 'موسلي', 'corn flakes', 'granola', 'muesli', 'cereal'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_breakfast_spreads',
        slug: 'breakfast-spreads',
        nameAr: 'سبريد وحشوات',
        nameEn: 'Spreads & Fillings',
        sortOrder: 20,
        keywordsAr: ['شوكولاتة قابلة للدهن', 'زبدة فول سوداني', 'طحينة', 'مربى', 'عسل', 'دبس'],
        keywordsEn: ['chocolate spread', 'peanut butter', 'tahini', 'jam', 'honey', 'molasses'],
        matchAlso: ['طحينه', 'نوتيلا', 'tahini', 'spread'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_breakfast_essentials',
        slug: 'breakfast-essentials',
        nameAr: 'مستلزمات الإفطار',
        nameEn: 'Breakfast Essentials',
        sortOrder: 30,
        keywordsAr: ['عسل', 'حلاوة طحينية', 'حلاوة بالمكسرات', 'زبدة', 'جبن للفطور'],
        keywordsEn: ['honey', 'halawa', 'tahini halva', 'breakfast cheese'],
        matchAlso: ['حلاوه', 'حلاوه طحينيه', 'halawa', 'halva'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 11. السناكس والمقرمشات ─────────────────────────────────────────────────────── */
  {
    id: 'cat_snacks', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'snacks',
    nameAr: 'السناكس والمقرمشات',
    nameEn: 'Snacks & Crisps',
    iconName: 'popcorn',
    colorTheme: 'violet',
    sortOrder: 1100,
    featured: false,
    children: [
      {
        id: 'cat_snacks_crisps',
        slug: 'snacks-crisps',
        nameAr: 'الشيبسي والمقرمشات',
        nameEn: 'Crisps & Savoury Snacks',
        sortOrder: 10,
        keywordsAr: ['شيبسي بطاطس', 'شيبسي جبنة', 'شيبسي شطة', 'شيبسي كاتشب', 'فشار جاهز', 'فشار ميكروويف', 'مقرمشات ذرة', 'مقرمشات جبنة'],
        keywordsEn: ['potato chips', 'crisps', 'cheese puffs', 'chilli chips', 'ketchup chips', 'popcorn', 'microwave popcorn', 'corn snacks'],
        matchAlso: ['شيبسي', 'مقرمشات', 'فشار', 'chips', 'crisps', 'popcorn', 'puffs'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_snacks_nuts',
        slug: 'snacks-nuts-seeds',
        nameAr: 'المكسرات والتسالي',
        nameEn: 'Nuts & Seeds',
        sortOrder: 30,
        keywordsAr: ['فول سوداني', 'لب أبيض', 'لب سوري', 'حمص محمص', 'فشار', 'لوز', 'كاجو', 'بندق', 'فستق', 'خلطات مكسرات'],
        keywordsEn: ['peanuts', 'melon seeds', 'sunflower seeds', 'roasted chickpeas', 'almonds', 'cashew', 'hazelnut', 'pistachio', 'mixed nuts'],
        matchAlso: ['مكسرات', 'لب', 'فول سوداني', 'لوز', 'كاجو', 'بندق', 'فستق', 'تمر', 'nuts', 'almond', 'cashew', 'peanut', 'dates'],
        forbidAny: [...NOT_FROZEN, 'زبده', 'butter'],
      },
    ],
  },

  /* ── 12. البسكويت والحلويات والشوكولاتة ─────────────────────────────────────────── */
  {
    id: 'cat_confectionery',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'confectionery',
    nameAr: 'البسكويت والحلويات والشوكولاتة',
    nameEn: 'Biscuits, Sweets & Chocolate',
    iconName: 'candy',
    colorTheme: 'rose',
    sortOrder: 1200,
    children: [
      {
        id: 'cat_conf_biscuits',
        slug: 'confectionery-biscuits',
        nameAr: 'البسكويت',
        nameEn: 'Biscuits',
        sortOrder: 10,
        keywordsAr: ['بسكويت سادة', 'بسكويت شاي', 'بسكويت ويفر', 'بسكويت محشو', 'بسكويت شوكولاتة', 'بسكويت كريمة', 'بسكويت دايجستيف'],
        keywordsEn: ['biscuit', 'tea biscuit', 'wafer', 'filled biscuit', 'chocolate biscuit', 'cream biscuit', 'digestive'],
        matchAlso: ['بسكويت', 'ويفر', 'biscuit', 'wafer', 'digestive'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_conf_chocolate',
        slug: 'confectionery-chocolate',
        nameAr: 'الشوكولاتة',
        nameEn: 'Chocolate',
        sortOrder: 20,
        keywordsAr: ['ألواح شوكولاتة', 'شوكولاتة سادة', 'شوكولاتة بالحليب', 'شوكولاتة مكسرات', 'شوكولاتة محشوة', 'شوكولاتة للطبخ'],
        keywordsEn: ['chocolate bar', 'dark chocolate', 'milk chocolate', 'nut chocolate', 'filled chocolate', 'cooking chocolate'],
        matchAlso: ['شوكولاته', 'chocolate'],
        forbidAny: [...NOT_FROZEN, 'قابله للدهن', 'spread'],
      },
      {
        id: 'cat_conf_candy',
        slug: 'confectionery-candy',
        nameAr: 'الحلوى',
        nameEn: 'Candy & Sweets',
        sortOrder: 30,
        keywordsAr: ['كاندي', 'علكة', 'مصاصات', 'جيلي', 'مارشميلو', 'توفي', 'كراميل'],
        keywordsEn: ['candy', 'chewing gum', 'lollipop', 'jelly', 'marshmallow', 'toffee', 'caramel'],
        matchAlso: ['حلوي', 'علكه', 'لبان', 'جيلي', 'مارشميلو', 'توفي', 'كراميل', 'candy', 'gum', 'jelly', 'toffee'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 13. المجمدات ──────────────────────────────────────────────────────────────── */
  {
    id: 'cat_frozen',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'frozen',
    nameAr: 'المجمدات',
    nameEn: 'Frozen Food',
    iconName: 'snowflake',
    colorTheme: 'blue',
    sortOrder: 1300,
    featured: false,
    children: [
      {
        id: 'cat_frozen_veg',
        slug: 'frozen-vegetables',
        nameAr: 'الخضروات المجمدة',
        nameEn: 'Frozen Vegetables',
        sortOrder: 10,
        keywordsAr: ['بسلة', 'بسلة وجزر', 'فاصوليا', 'بامية', 'ملوخية', 'سبانخ', 'خضار مشكل', 'ذرة'],
        keywordsEn: ['frozen peas', 'peas and carrots', 'frozen beans', 'okra', 'molokhia', 'spinach', 'mixed vegetables', 'frozen corn'],
        matchAlso: ['بسله', 'باميه', 'ملوخيه', 'سبانخ', 'okra', 'spinach', 'molokhia'],
        requireAny: FREEZER_TOKENS,
      },
      {
        id: 'cat_frozen_potato',
        slug: 'frozen-potatoes',
        nameAr: 'البطاطس والمقبلات المجمدة',
        nameEn: 'Frozen Potatoes & Appetisers',
        sortOrder: 20,
        keywordsAr: ['بطاطس أصابع', 'بطاطس حلقات', 'بطاطس ودجز', 'هاش براون', 'بطاطس محشوة', 'كروكيت'],
        keywordsEn: ['french fries', 'potato rings', 'wedges', 'hash brown', 'stuffed potato', 'croquette'],
        matchAlso: ['بطاطس', 'هاش براون', 'كروكيت', 'fries', 'wedges', 'hash brown'],
        requireAny: FREEZER_TOKENS,
      },
      {
        id: 'cat_frozen_poultry',
        slug: 'frozen-poultry',
        nameAr: 'الدواجن المجمدة',
        nameEn: 'Frozen Poultry',
        sortOrder: 30,
        keywordsAr: ['دجاج كامل', 'صدور دجاج', 'أوراك', 'أجنحة', 'دبابيس', 'كبد وقوانص'],
        keywordsEn: ['whole chicken', 'chicken breast', 'thighs', 'wings', 'drumsticks', 'liver and gizzards'],
        matchAlso: ['دجاج', 'فراخ', 'ديك رومي', 'تركي', 'chicken', 'poultry', 'turkey'],
        requireAny: FREEZER_TOKENS,
      },
      {
        id: 'cat_frozen_meat',
        slug: 'frozen-meat',
        nameAr: 'اللحوم المجمدة',
        nameEn: 'Frozen Meat',
        sortOrder: 40,
        keywordsAr: ['لحم مفروم', 'برجر', 'كفتة', 'سجق', 'كباب', 'شاورما'],
        keywordsEn: ['minced meat', 'burger', 'kofta', 'sausage', 'kebab', 'shawarma'],
        matchAlso: ['لحم', 'برجر', 'كفته', 'كباب', 'beef', 'burger', 'kofta'],
        requireAny: FREEZER_TOKENS,
      },
      {
        id: 'cat_frozen_seafood',
        slug: 'frozen-seafood',
        nameAr: 'الأسماك والمأكولات البحرية',
        nameEn: 'Frozen Fish & Seafood',
        sortOrder: 50,
        keywordsAr: ['سمك فيليه', 'جمبري', 'كاليماري', 'بانيه سمك', 'أصابع سمك'],
        keywordsEn: ['fish fillet', 'shrimp', 'calamari', 'fish pane', 'fish fingers'],
        matchAlso: ['سمك', 'جمبري', 'كاليماري', 'fish', 'shrimp', 'calamari'],
        requireAny: FREEZER_TOKENS,
      },
      {
        id: 'cat_frozen_icecream',
        slug: 'frozen-ice-cream',
        nameAr: 'الآيس كريم',
        nameEn: 'Ice Cream',
        sortOrder: 70,
        keywordsAr: ['آيس كريم عبوات', 'آيس كريم فردي', 'مثلجات عصا', 'ساندويتش آيس كريم', 'آيس كريم عائلي'],
        keywordsEn: ['ice cream', 'ice cream tub', 'ice cream stick', 'ice cream sandwich', 'family ice cream'],
        matchAlso: ['ايس كريم', 'مثلجات', 'ice cream'],
        requireAny: ['ايس كريم', 'ايسكريم', 'مثلجات', 'ice cream', 'icecream'],
      },
    ],
  },

  /* ── 14. الفاكهة والخضروات الطازجة ──────────────────────────────────────────────── */
  {
    id: 'cat_fresh', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'fresh-produce',
    nameAr: 'الفاكهة والخضروات الطازجة',
    nameEn: 'Fresh Produce',
    iconName: 'carrot',
    colorTheme: 'green',
    sortOrder: 1400,
    featured: false,
    children: [
      {
        id: 'cat_fresh_veg',
        slug: 'fresh-produce-vegetables',
        nameAr: 'الخضروات',
        nameEn: 'Vegetables',
        sortOrder: 10,
        keywordsAr: ['طماطم', 'بطاطس', 'بصل', 'ثوم', 'خيار', 'فلفل', 'جزر', 'كوسة', 'باذنجان', 'بسلة', 'فاصوليا', 'ملوخية', 'سبانخ', 'خس', 'كرنب', 'قرنبيط', 'بروكلي'],
        keywordsEn: ['tomato', 'potato', 'onion', 'garlic', 'cucumber', 'pepper', 'carrot', 'courgette', 'aubergine', 'peas', 'beans', 'molokhia', 'spinach', 'lettuce', 'cabbage', 'cauliflower', 'broccoli'],
        matchAlso: ['طماطم', 'بطاطس', 'بصل', 'ثوم', 'خيار', 'فلفل', 'جزر', 'كوسه', 'باذنجان', 'خس', 'كرنب', 'قرنبيط', 'بروكلي'],
        forbidAny: FRESH_ONLY,
      },
      {
        id: 'cat_fresh_fruit',
        slug: 'fresh-produce-fruits',
        nameAr: 'الفاكهة',
        nameEn: 'Fruits',
        sortOrder: 20,
        keywordsAr: ['برتقال', 'يوسفي', 'تفاح', 'موز', 'مانجو', 'فراولة', 'جوافة', 'كمثرى', 'عنب', 'بطيخ', 'شمام', 'خوخ', 'برقوق', 'كيوي', 'أناناس'],
        keywordsEn: ['orange', 'mandarin', 'apple', 'banana', 'mango', 'strawberry', 'guava', 'pear', 'grapes', 'watermelon', 'melon', 'peach', 'plum', 'kiwi', 'pineapple'],
        matchAlso: ['برتقال', 'يوسفي', 'تفاح', 'موز', 'مانجو', 'فراوله', 'جوافه', 'كمثري', 'عنب', 'بطيخ', 'شمام', 'خوخ', 'كيوي', 'اناناس'],
        forbidAny: FRESH_ONLY,
      },
      {
        id: 'cat_fresh_herbs',
        slug: 'fresh-produce-herbs',
        nameAr: 'الأعشاب والخضرة',
        nameEn: 'Fresh Herbs & Greens',
        sortOrder: 30,
        keywordsAr: ['بقدونس', 'كزبرة', 'شبت', 'نعناع', 'جرجير', 'كرفس'],
        keywordsEn: ['parsley', 'coriander', 'dill', 'mint', 'rocket', 'celery'],
        matchAlso: ['بقدونس', 'كزبره', 'شبت', 'نعناع', 'جرجير', 'كرفس'],
        forbidAny: FRESH_ONLY,
      },
    ],
  },

  /* ── 15. المنتجات الغذائية الجاهزة وشبه الجاهزة ─────────────────────────────────── */
  {
    id: 'cat_ready',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'ready-foods',
    nameAr: 'المنتجات الجاهزة وشبه الجاهزة',
    nameEn: 'Ready & Semi-Ready Foods',
    iconName: 'soup',
    colorTheme: 'brand',
    sortOrder: 1500,
    children: [
      {
        id: 'cat_ready_soup',
        slug: 'ready-foods-soups',
        nameAr: 'الشوربات',
        nameEn: 'Soups',
        sortOrder: 10,
        keywordsAr: ['شوربة خضار', 'شوربة دجاج', 'شوربة مشروم', 'شوربة عدس', 'شوربة جاهزة للتحضير'],
        keywordsEn: ['vegetable soup', 'chicken soup', 'mushroom soup', 'lentil soup', 'instant soup'],
        matchAlso: ['شوربه', 'soup'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_ready_instant',
        slug: 'ready-foods-instant',
        nameAr: 'المنتجات سريعة التحضير',
        nameEn: 'Instant Foods',
        sortOrder: 20,
        keywordsAr: ['نودلز', 'مكرونة سريعة التحضير', 'شوربة سريعة التحضير', 'بطاطس سريعة التحضير', 'أرز سريع التحضير'],
        keywordsEn: ['noodles', 'instant noodles', 'instant pasta', 'instant soup', 'instant potato', 'instant rice'],
        matchAlso: ['نودلز', 'سريعه التحضير', 'سريع التحضير', 'noodles', 'instant'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_ready_cooking',
        slug: 'ready-foods-cooking-aids',
        nameAr: 'مستلزمات الطبخ الجاهزة',
        nameEn: 'Cooking Aids',
        sortOrder: 30,
        keywordsAr: ['مرقة دجاج', 'مرقة لحوم', 'مرقة خضار', 'خلطات بشاميل', 'خلطات كيك', 'خلطات بان كيك'],
        keywordsEn: ['chicken stock', 'beef stock', 'vegetable stock', 'bouillon', 'bechamel mix', 'cake mix', 'pancake mix'],
        matchAlso: ['مرقه', 'مكعبات مرقه', 'بشاميل', 'stock', 'bouillon', 'bechamel'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ── 16. المنظفات والعناية بالمنزل ──────────────────────────────────────────────── */
  {
    id: 'cat_cleaning', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'cleaning',
    nameAr: 'المنظفات والعناية بالمنزل',
    nameEn: 'Cleaning & Home Care',
    iconName: 'spray-can',
    colorTheme: 'green',
    sortOrder: 1600,
    children: [
      {
        id: 'cat_clean_laundry',
        slug: 'cleaning-laundry',
        nameAr: 'منظفات الغسيل',
        nameEn: 'Laundry Detergents',
        sortOrder: 10,
        keywordsAr: ['مسحوق غسيل', 'جل غسيل', 'سائل غسيل', 'مسحوق للغسالات الأوتوماتيك', 'مزيل بقع', 'مبيض', 'منعم أقمشة'],
        keywordsEn: ['washing powder', 'laundry gel', 'liquid detergent', 'automatic powder', 'stain remover', 'bleach', 'fabric softener'],
        matchAlso: ['مسحوق غسيل', 'منظف غسيل', 'منعم', 'مبيض', 'كلور', 'detergent', 'softener', 'bleach'],
      },
      {
        id: 'cat_clean_dish',
        slug: 'cleaning-dishwashing',
        nameAr: 'منظفات الأطباق',
        nameEn: 'Dishwashing',
        sortOrder: 20,
        keywordsAr: ['سائل غسيل أطباق', 'أقراص غسالة أطباق', 'جل غسالة أطباق', 'ملمع غسالة أطباق'],
        keywordsEn: ['dishwashing liquid', 'dishwasher tablets', 'dishwasher gel', 'rinse aid'],
        matchAlso: ['غسيل اطباق', 'مواعين', 'dishwash'],
      },
      {
        id: 'cat_clean_surfaces',
        slug: 'cleaning-surfaces',
        nameAr: 'منظفات الأرضيات والأسطح',
        nameEn: 'Floor & Surface Cleaners',
        sortOrder: 30,
        keywordsAr: ['منظف أرضيات', 'منظف متعدد الاستخدام', 'منظف زجاج', 'منظف مطابخ', 'منظف حمامات', 'مطهر', 'مزيل دهون', 'ملمع أثاث'],
        keywordsEn: ['floor cleaner', 'multi purpose cleaner', 'glass cleaner', 'kitchen cleaner', 'bathroom cleaner', 'degreaser', 'furniture polish'],
        matchAlso: ['منظف', 'ملمع', 'مزيل دهون', 'cleaner', 'polish'],
      },
      {
        id: 'cat_clean_disinfect',
        slug: 'cleaning-disinfectants',
        nameAr: 'المطهرات والمعطرات',
        nameEn: 'Disinfectants & Air Fresheners',
        sortOrder: 40,
        keywordsAr: ['كلور', 'مطهر أسطح', 'معطر جو', 'معطر مفروشات', 'معطر حمام', 'مزيل روائح'],
        keywordsEn: ['chlorine', 'surface disinfectant', 'air freshener', 'fabric freshener', 'toilet freshener', 'odour remover'],
        matchAlso: ['معطر', 'مطهر', 'مبيد', 'air freshener', 'disinfectant', 'insecticide'],
      },
      {
        id: 'cat_clean_tools',
        slug: 'cleaning-tools',
        nameAr: 'أدوات التنظيف',
        nameEn: 'Cleaning Tools',
        sortOrder: 50,
        keywordsAr: ['إسفنج مواعين', 'ليفة تنظيف', 'سلك مواعين', 'فرشاة تنظيف', 'ممسحة', 'جردل', 'مكنسة', 'جاروف', 'قفازات تنظيف'],
        keywordsEn: ['sponge', 'scourer', 'steel wool', 'cleaning brush', 'mop', 'bucket', 'broom', 'dustpan', 'cleaning gloves'],
        matchAlso: ['اسفنج', 'ليفه', 'سلك', 'فرشاه', 'ممسحه', 'مكنسه', 'جردل', 'قفازات', 'sponge', 'mop', 'broom', 'brush'],
      },
    ],
  },

  /* ── 17. الورقيات والمناديل ─────────────────────────────────────────────────────── */
  {
    id: 'cat_paper',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'paper-tissues',
    nameAr: 'الورقيات والمناديل',
    nameEn: 'Paper & Tissues',
    iconName: 'scroll-text',
    colorTheme: 'blue',
    sortOrder: 1700,
    children: [
      {
        id: 'cat_paper_tissues',
        slug: 'paper-tissues-facial',
        nameAr: 'المناديل الورقية',
        nameEn: 'Tissues',
        sortOrder: 10,
        keywordsAr: ['مناديل وجه', 'مناديل جيب', 'مناديل سفرة', 'مناديل مطبخ'],
        keywordsEn: ['facial tissue', 'pocket tissue', 'table napkins', 'kitchen towel'],
        matchAlso: ['مناديل', 'tissue', 'napkin'],
      },
      {
        id: 'cat_paper_household',
        slug: 'paper-tissues-household',
        nameAr: 'ورق الاستخدام المنزلي',
        nameEn: 'Household Paper',
        sortOrder: 20,
        keywordsAr: ['ورق تواليت', 'رول مطبخ', 'ورق ألومنيوم', 'ورق زبدة', 'أكياس فرن'],
        keywordsEn: ['toilet paper', 'kitchen roll', 'aluminium foil', 'baking paper', 'oven bags'],
        matchAlso: ['ورق توالت', 'رول مطبخ', 'فويل', 'ورق زبده', 'toilet paper', 'kitchen roll', 'foil'],
      },
      {
        id: 'cat_paper_other',
        slug: 'paper-tissues-other',
        nameAr: 'المنتجات الورقية الأخرى',
        nameEn: 'Other Paper Products',
        sortOrder: 30,
        keywordsAr: ['أكواب ورقية', 'أطباق ورقية', 'مناديل مبللة', 'مناديل تعقيم'],
        keywordsEn: ['paper cups', 'paper plates', 'wet wipes', 'sanitising wipes'],
        matchAlso: ['مناديل مبلله', 'اكواب ورقيه', 'اطباق ورقيه', 'wet wipes', 'paper cups'],
      },
    ],
  },

  /* ── 18. العناية الشخصية ────────────────────────────────────────────────────────── */
  {
    id: 'cat_care', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'personal-care',
    nameAr: 'العناية الشخصية',
    nameEn: 'Personal Care',
    iconName: 'sparkles',
    colorTheme: 'brand',
    sortOrder: 1800,
    children: [
      {
        id: 'cat_care_body',
        slug: 'personal-care-bath-body',
        nameAr: 'الاستحمام والجسم',
        nameEn: 'Bath & Body',
        sortOrder: 10,
        keywordsAr: ['صابون', 'شاور جل', 'لوشن جسم', 'كريم جسم', 'مزيل عرق', 'إسفنجة استحمام'],
        keywordsEn: ['soap', 'shower gel', 'body lotion', 'body cream', 'deodorant', 'bath sponge'],
        matchAlso: ['صابون', 'شاور جل', 'لوشن', 'كريم جسم', 'مزيل عرق', 'soap', 'shower gel', 'lotion', 'deodorant'],
      },
      {
        id: 'cat_care_hair',
        slug: 'personal-care-hair',
        nameAr: 'الشعر',
        nameEn: 'Hair Care',
        sortOrder: 20,
        keywordsAr: ['شامبو', 'بلسم', 'كريم شعر', 'زيت شعر', 'ماسك شعر', 'جل شعر', 'سبراي شعر'],
        keywordsEn: ['shampoo', 'conditioner', 'hair cream', 'hair oil', 'hair mask', 'hair gel', 'hair spray'],
        matchAlso: ['شامبو', 'بلسم', 'كريم شعر', 'زيت شعر', 'صبغه', 'shampoo', 'conditioner', 'hair'],
      },
      {
        id: 'cat_care_oral',
        slug: 'personal-care-oral',
        nameAr: 'الأسنان والفم',
        nameEn: 'Oral Care',
        sortOrder: 30,
        keywordsAr: ['معجون أسنان', 'فرشاة أسنان', 'غسول فم', 'خيط أسنان', 'أعواد تنظيف الأسنان'],
        keywordsEn: ['toothpaste', 'toothbrush', 'mouthwash', 'dental floss', 'toothpicks'],
        matchAlso: ['معجون اسنان', 'فرشاه اسنان', 'غسول فم', 'toothpaste', 'toothbrush', 'mouthwash'],
      },
      {
        id: 'cat_care_shaving',
        slug: 'personal-care-shaving',
        nameAr: 'الحلاقة',
        nameEn: 'Shaving',
        sortOrder: 40,
        keywordsAr: ['شفرات حلاقة', 'ماكينات حلاقة', 'كريم حلاقة', 'جل حلاقة', 'أفتر شيف'],
        keywordsEn: ['razor blades', 'razor', 'shaving cream', 'shaving gel', 'after shave'],
        matchAlso: ['شفرات', 'ماكينه حلاقه', 'كريم حلاقه', 'razor', 'shaving'],
      },
      {
        id: 'cat_care_feminine',
        slug: 'personal-care-feminine',
        nameAr: 'العناية النسائية',
        nameEn: 'Feminine Care',
        sortOrder: 50,
        keywordsAr: ['فوط صحية', 'فوط يومية', 'منتجات نسائية للعناية الشخصية', 'مناديل مبللة نسائية'],
        keywordsEn: ['sanitary pads', 'daily liners', 'feminine wash', 'feminine wipes'],
        matchAlso: ['فوط صحيه', 'sanitary', 'feminine'],
      },
    ],
  },

  /* ── 19. مستلزمات الأطفال ───────────────────────────────────────────────────────── */
  {
    id: 'cat_baby',
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'baby',
    nameAr: 'مستلزمات الأطفال',
    nameEn: 'Baby Care',
    iconName: 'baby',
    colorTheme: 'rose',
    sortOrder: 1900,
    children: [
      {
        id: 'cat_baby_nappies',
        slug: 'baby-nappies',
        nameAr: 'الحفاضات',
        nameEn: 'Nappies',
        sortOrder: 10,
        keywordsAr: ['حفاضات أطفال', 'حفاضات حديثي الولادة', 'حفاضات سباحة', 'حفاضات مقاسات مختلفة'],
        keywordsEn: ['baby diapers', 'nappies', 'newborn diapers', 'swim diapers'],
        matchAlso: ['حفاضات', 'حفاضه', 'diaper', 'nappy'],
      },
      {
        id: 'cat_baby_care',
        slug: 'baby-care-products',
        nameAr: 'العناية بالطفل',
        nameEn: 'Baby Toiletries',
        sortOrder: 20,
        keywordsAr: ['شامبو أطفال', 'صابون أطفال', 'كريم حفاضات', 'زيت أطفال', 'لوشن أطفال', 'مناديل مبللة'],
        keywordsEn: ['baby shampoo', 'baby soap', 'nappy cream', 'baby oil', 'baby lotion', 'baby wipes'],
        matchAlso: ['شامبو اطفال', 'كريم حفاضات', 'baby shampoo', 'baby wipes'],
      },
      {
        id: 'cat_baby_food',
        slug: 'baby-food',
        nameAr: 'غذاء الأطفال',
        nameEn: 'Baby Food',
        sortOrder: 30,
        keywordsAr: ['ألبان أطفال', 'حبوب أطفال', 'وجبات أطفال', 'سيريلاك', 'عصائر أطفال', 'سناكس أطفال'],
        keywordsEn: ['infant formula', 'baby cereal', 'baby meals', 'cerelac', 'baby juice', 'baby snacks'],
        matchAlso: ['سيريلاك', 'حليب رضع', 'لبن اطفال', 'طعام اطفال', 'formula', 'cerelac'],
      },
      {
        id: 'cat_baby_accessories',
        slug: 'baby-accessories',
        nameAr: 'مستلزمات الأطفال',
        nameEn: 'Baby Accessories',
        sortOrder: 40,
        keywordsAr: ['ببرونات', 'حلمات رضاعة', 'لهايات', 'زجاجات أطفال', 'فرش تنظيف الببرونات'],
        keywordsEn: ['baby bottles', 'teats', 'pacifiers', 'bottle brush'],
        matchAlso: ['ببرونه', 'ببرونات', 'لهايه', 'حلمه', 'pacifier', 'feeding bottle'],
      },
    ],
  },

  /* ── الصيدلية والتموين — the reused catch-all staples department ──────────────────── */
  /* Not a numbered section in the brief, but cat_groceries is one of the 8 seeded ids and
     is referenced by seed.ts PROMOTIONS and catalog.integration.test.ts (slug 'groceries').
     Retained as the home for ambient staples that do not belong to a numbered section. */
  {
    id: 'cat_groceries', // REUSED
    isActive: false, // deactivated: 0 real products until a grocery source is imported (chefaa import covers pharmacy/beauty/baby only)
    slug: 'groceries',
    nameAr: 'الصيدلية والتموين',
    nameEn: 'Groceries & Pantry',
    iconName: 'shopping-basket',
    colorTheme: 'brand',
    sortOrder: 2500,
    // Un-featured: 0 real products until a grocery source is imported (was one of the 4
    // originally-seeded featured categories — see cat_med etc. below for real content now).
    featured: false,
    children: [
      {
        id: 'cat_groc_staples',
        slug: 'groceries-staples',
        nameAr: 'سلع أساسية',
        nameEn: 'Pantry Staples',
        sortOrder: 10,
        keywordsAr: ['سلع أساسية', 'تموين', 'مواد غذائية جافة'],
        keywordsEn: ['pantry staples', 'dry goods', 'grocery essentials'],
        matchAlso: ['تموين'],
        forbidAny: NOT_FROZEN,
      },
      {
        id: 'cat_groc_pickles',
        slug: 'groceries-pickles-olives',
        nameAr: 'المخللات والزيتون',
        nameEn: 'Pickles & Olives',
        sortOrder: 20,
        keywordsAr: ['مخللات', 'خيار مخلل', 'لفت', 'زيتون أخضر', 'زيتون أسود', 'ليمون مخلل'],
        keywordsEn: ['pickles', 'pickled cucumber', 'turnip', 'green olives', 'black olives', 'pickled lemon'],
        matchAlso: ['مخلل', 'مخللات', 'زيتون', 'pickle', 'olives'],
        forbidAny: NOT_FROZEN,
      },
    ],
  },

  /* ═══════════════════════════════════════════════════════════════════════════════════
   * CHEFAA PHARMACY IMPORT (§catalog import — chefaa source)
   *
   * The grocery brief above has no medicine, hair/skin-care, makeup, vitamins, sexual
   * wellness, medical-device or pet department, yet those are most of what an online
   * pharmacy sells. These 11 parents mirror chefaa.com's own top-level nav and its
   * department pages' own subcategory chips 1:1 (names, structure and level_two slugs
   * verified live against https://chefaa.com/eg-ar on 2026-09-24), so the storefront
   * reads as chefaa's real taxonomy rather than a keyword guess.
   *
   * Classification for chefaa products does NOT go through classify.ts / SOURCE_RULES —
   * chefaa's own search index already carries a clean level_one/level_two category on
   * every product, so ingest/sources/chefaa/mapping.ts maps that pair straight to the
   * leaf id below (see CHEFAA_CATEGORY_MAP). keywordsAr/keywordsEn are still populated
   * (the leaf's own bilingual name) purely to satisfy the "every leaf has a tag
   * vocabulary" invariant (taxonomy.test.ts) and to let the generic classifier reuse
   * these leaves for some OTHER source later if one ever needs to.
   *
   * chefaa's own 3rd category level (e.g. narrow health conditions like "دوخة"، "حروق")
   * is sparse and — per this file's own two-level rule — becomes product `tags`, never
   * a categories row.
   * ═══════════════════════════════════════════════════════════════════════════════════ */

  /* ── chefaa 1. الأدوية (Medications) ──────────────────────────────────────────────── */
  {
    id: 'cat_med',
    slug: 'medications',
    nameAr: 'الأدوية',
    nameEn: 'Medications',
    iconName: 'pill',
    colorTheme: 'rose',
    sortOrder: 3000,
    featured: true,
    children: [
      {
        id: 'cat_med_health_condition',
        slug: 'medications-health-condition',
        nameAr: 'حسب الحالة الصحية',
        nameEn: 'By Health Condition',
        sortOrder: 10,
        keywordsAr: ['حسب الحالة الصحية'],
        keywordsEn: ['By Health Condition'],
      },
      {
        id: 'cat_med_cough_cold',
        slug: 'medications-cough-cold-allergy',
        nameAr: 'أدوية الكحة والزكام',
        nameEn: 'Cough, Cold & Allergy',
        sortOrder: 20,
        keywordsAr: ['أدوية الكحة والزكام'],
        keywordsEn: ['Cough, Cold & Allergy'],
      },
      {
        id: 'cat_med_eye_ear',
        slug: 'medications-eye-ear',
        nameAr: 'قطرات العين والأذن',
        nameEn: 'Eye & Ear Drops',
        sortOrder: 30,
        keywordsAr: ['قطرات العين والأذن'],
        keywordsEn: ['Eye & Ear Drops'],
      },
      {
        id: 'cat_med_kids',
        slug: 'medications-kids-infant',
        nameAr: 'أدوية الأطفال',
        nameEn: 'Kids & Infant Medications',
        sortOrder: 40,
        keywordsAr: ['أدوية الأطفال'],
        keywordsEn: ['Kids & Infant Medications'],
      },
      {
        id: 'cat_med_stomach',
        slug: 'medications-stomach-bowel',
        nameAr: 'أدوية المعدة والقولون',
        nameEn: 'Stomach & Bowel',
        sortOrder: 50,
        keywordsAr: ['أدوية المعدة والقولون'],
        keywordsEn: ['Stomach & Bowel'],
      },
      {
        id: 'cat_med_pain_relief',
        slug: 'medications-pain-relief',
        nameAr: 'مسكنات الألم',
        nameEn: 'Pain Relief',
        sortOrder: 60,
        keywordsAr: ['مسكنات الألم'],
        keywordsEn: ['Pain Relief'],
      },
      {
        id: 'cat_med_skin',
        slug: 'medications-skin-treatments',
        nameAr: 'أدوية الجلدية',
        nameEn: 'Skin Treatments',
        sortOrder: 70,
        keywordsAr: ['أدوية الجلدية'],
        keywordsEn: ['Skin Treatments'],
      },
      {
        id: 'cat_med_allergy',
        slug: 'medications-allergy',
        nameAr: 'الحساسية',
        nameEn: 'Allergy',
        sortOrder: 80,
        keywordsAr: ['الحساسية'],
        keywordsEn: ['Allergy'],
      },
      {
        // Safety-net leaf: a chefaa product tagged only "Medications" with no subcategory
        // still needs a leaf (products.category_id has no "parent-only" placement) — see
        // ingest/sources/chefaa/mapping.ts LEVEL_ONE_FALLBACK.
        id: 'cat_med_other',
        slug: 'medications-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 90,
        keywordsAr: ['أدوية أخرى'],
        keywordsEn: ['Other Medications'],
      },
    ],
  },

  /* ── chefaa 2. العناية بالشعر (Hair Care) ─────────────────────────────────────────── */
  {
    id: 'cat_hair',
    slug: 'hair-care',
    nameAr: 'العناية بالشعر',
    nameEn: 'Hair Care',
    iconName: 'scissors',
    colorTheme: 'blue',
    sortOrder: 3100,
    featured: true,
    children: [
      {
        id: 'cat_hair_shampoo',
        slug: 'hair-care-shampoo-conditioner',
        nameAr: 'شامبو وبلسم',
        nameEn: 'Shampoo & Conditioner',
        sortOrder: 10,
        keywordsAr: ['شامبو وبلسم'],
        keywordsEn: ['Shampoo & Conditioner'],
      },
      {
        id: 'cat_hair_treatment',
        slug: 'hair-care-nourishment-treatment',
        nameAr: 'ترطيب وعلاج الشعر',
        nameEn: 'Nourishment & Treatment',
        sortOrder: 20,
        keywordsAr: ['ترطيب وعلاج الشعر'],
        keywordsEn: ['Nourishment & Treatment'],
      },
      {
        id: 'cat_hair_styling',
        slug: 'hair-care-styling-devices',
        nameAr: 'اجهزة تصفيف الشعر',
        nameEn: 'Hair Styling Devices',
        sortOrder: 30,
        keywordsAr: ['اجهزة تصفيف الشعر'],
        keywordsEn: ['Hair Styling Devices'],
      },
      {
        id: 'cat_hair_coloring',
        slug: 'hair-care-coloring',
        nameAr: 'صبغات الشعر',
        nameEn: 'Hair Coloring',
        sortOrder: 40,
        keywordsAr: ['صبغات الشعر'],
        keywordsEn: ['Hair Coloring'],
      },
      {
        id: 'cat_hair_other',
        slug: 'hair-care-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 50,
        keywordsAr: ['عناية شعر أخرى'],
        keywordsEn: ['Other Hair Care'],
      },
    ],
  },

  /* ── chefaa 3. العناية بالبشرة (Skin Care) ────────────────────────────────────────── */
  {
    id: 'cat_skin',
    slug: 'skin-care',
    nameAr: 'العناية بالبشرة',
    nameEn: 'Skin Care',
    iconName: 'sparkles',
    colorTheme: 'violet',
    sortOrder: 3200,
    featured: true,
    children: [
      {
        id: 'cat_skin_cleansers',
        slug: 'skin-care-cleansers',
        nameAr: 'الغسول',
        nameEn: 'Cleansers',
        sortOrder: 10,
        keywordsAr: ['الغسول'],
        keywordsEn: ['Cleansers'],
      },
      {
        id: 'cat_skin_moisturizers',
        slug: 'skin-care-moisturizers',
        nameAr: 'الترطيب',
        nameEn: 'Moisturizers',
        sortOrder: 20,
        keywordsAr: ['الترطيب'],
        keywordsEn: ['Moisturizers'],
      },
      {
        id: 'cat_skin_serum',
        slug: 'skin-care-serum',
        nameAr: 'السيروم',
        nameEn: 'Serum',
        sortOrder: 30,
        keywordsAr: ['السيروم'],
        keywordsEn: ['Serum'],
      },
      {
        id: 'cat_skin_masks',
        slug: 'skin-care-masks',
        nameAr: 'الماسك',
        nameEn: 'Masks',
        sortOrder: 40,
        keywordsAr: ['الماسك'],
        keywordsEn: ['Masks'],
      },
      {
        id: 'cat_skin_sun',
        slug: 'skin-care-sun-care',
        nameAr: 'الوقاية من الشمس',
        nameEn: 'Sun Care',
        sortOrder: 50,
        keywordsAr: ['الوقاية من الشمس'],
        keywordsEn: ['Sun Care'],
      },
      {
        id: 'cat_skin_eye',
        slug: 'skin-care-eye-care',
        nameAr: 'العناية بالعيون',
        nameEn: 'Eye Care',
        sortOrder: 60,
        keywordsAr: ['العناية بالعيون'],
        keywordsEn: ['Eye Care'],
      },
      {
        id: 'cat_skin_other',
        slug: 'skin-care-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 70,
        keywordsAr: ['عناية بشرة أخرى'],
        keywordsEn: ['Other Skin Care'],
      },
    ],
  },

  /* ── chefaa 4. العناية اليومية (Daily Essentials) ─────────────────────────────────── */
  {
    id: 'cat_daily',
    slug: 'daily-essentials',
    nameAr: 'العناية اليومية',
    nameEn: 'Daily Essentials',
    iconName: 'spray-can',
    colorTheme: 'green',
    sortOrder: 3300,
    featured: true,
    children: [
      {
        id: 'cat_daily_bath',
        slug: 'daily-essentials-bath-body',
        nameAr: 'العناية بالجسم و الاستحمام',
        nameEn: 'Bath & Body Care',
        sortOrder: 10,
        keywordsAr: ['العناية بالجسم و الاستحمام'],
        keywordsEn: ['Bath & Body Care'],
      },
      {
        id: 'cat_daily_oral',
        slug: 'daily-essentials-oral-care',
        nameAr: 'العناية بالفم و الاسنان',
        nameEn: 'Oral Care',
        sortOrder: 20,
        keywordsAr: ['العناية بالفم و الاسنان'],
        keywordsEn: ['Oral Care'],
      },
      {
        id: 'cat_daily_feminine',
        slug: 'daily-essentials-feminine-care',
        nameAr: 'العناية النسائية',
        nameEn: 'Feminine Care',
        sortOrder: 30,
        keywordsAr: ['العناية النسائية'],
        keywordsEn: ['Feminine Care'],
      },
      {
        id: 'cat_daily_men',
        slug: 'daily-essentials-men-care',
        nameAr: 'العناية الرجالية',
        nameEn: 'Men Care',
        sortOrder: 40,
        keywordsAr: ['العناية الرجالية'],
        keywordsEn: ['Men Care'],
      },
      {
        id: 'cat_daily_protection',
        slug: 'daily-essentials-protection',
        nameAr: 'الحماية',
        nameEn: 'Protection',
        sortOrder: 50,
        keywordsAr: ['الحماية'],
        keywordsEn: ['Protection'],
      },
      {
        id: 'cat_daily_herbs',
        slug: 'daily-essentials-natural-herbs',
        nameAr: 'الأعشاب الطبيعية و الفيتامينات',
        nameEn: 'Natural Herbs & Vitamins',
        sortOrder: 60,
        keywordsAr: ['الأعشاب الطبيعية و الفيتامينات'],
        keywordsEn: ['Natural Herbs & Vitamins'],
      },
      {
        id: 'cat_daily_other',
        slug: 'daily-essentials-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 70,
        keywordsAr: ['عناية يومية أخرى'],
        keywordsEn: ['Other Daily Essentials'],
      },
    ],
  },

  /* ── chefaa 5. الأم والطفل (Mom & Baby) ───────────────────────────────────────────── */
  {
    id: 'cat_mombaby',
    slug: 'mom-baby',
    nameAr: 'الأم والطفل',
    nameEn: 'Mom & Baby',
    iconName: 'baby',
    colorTheme: 'orange',
    sortOrder: 3400,
    featured: true,
    children: [
      {
        id: 'cat_mombaby_diapers',
        slug: 'mom-baby-diapers-changing',
        nameAr: 'الحفاضات و مستحضرات التغيير',
        nameEn: 'Diapers & Changing',
        sortOrder: 10,
        keywordsAr: ['الحفاضات و مستحضرات التغيير'],
        keywordsEn: ['Diapers & Changing'],
      },
      {
        id: 'cat_mombaby_mommy',
        slug: 'mom-baby-mommy-care',
        nameAr: 'العناية بالام',
        nameEn: 'Mommy Care',
        sortOrder: 20,
        keywordsAr: ['العناية بالام'],
        keywordsEn: ['Mommy Care'],
      },
      {
        id: 'cat_mombaby_food',
        slug: 'mom-baby-baby-food-tools',
        nameAr: 'طعام الاطفال و مستلزماته',
        nameEn: 'Baby Food & Tools',
        sortOrder: 30,
        keywordsAr: ['طعام الاطفال و مستلزماته'],
        keywordsEn: ['Baby Food & Tools'],
      },
      {
        id: 'cat_mombaby_breastfeeding',
        slug: 'mom-baby-breastfeeding-care',
        nameAr: 'مستلزمات الرضاعة الطبيعية',
        nameEn: 'Breastfeeding Care',
        sortOrder: 40,
        keywordsAr: ['مستلزمات الرضاعة الطبيعية'],
        keywordsEn: ['Breastfeeding Care'],
      },
      {
        id: 'cat_mombaby_bathing',
        slug: 'mom-baby-bathing-baby-care',
        nameAr: 'الاستحمام',
        nameEn: 'Bathing & Baby Care',
        sortOrder: 50,
        keywordsAr: ['الاستحمام'],
        keywordsEn: ['Bathing & Baby Care'],
      },
      {
        id: 'cat_mombaby_other',
        slug: 'mom-baby-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 60,
        keywordsAr: ['مستلزمات أم وطفل أخرى'],
        keywordsEn: ['Other Mom & Baby'],
      },
    ],
  },

  /* ── chefaa 6. المكياج والاكسسوارات (Makeup & Accessories) ───────────────────────── */
  {
    id: 'cat_makeup',
    slug: 'makeup-accessories',
    nameAr: 'المكياج والاكسسوارات',
    nameEn: 'Makeup & Accessories',
    iconName: 'palette',
    colorTheme: 'rose',
    sortOrder: 3500,
    featured: true,
    children: [
      {
        id: 'cat_makeup_face',
        slug: 'makeup-accessories-face',
        nameAr: 'الوجه',
        nameEn: 'Face',
        sortOrder: 10,
        keywordsAr: ['الوجه'],
        keywordsEn: ['Face'],
      },
      {
        id: 'cat_makeup_eyes',
        slug: 'makeup-accessories-eyes',
        nameAr: 'العيون',
        nameEn: 'Eyes',
        sortOrder: 20,
        keywordsAr: ['العيون'],
        keywordsEn: ['Eyes'],
      },
      {
        id: 'cat_makeup_eyelashes',
        slug: 'makeup-accessories-eyelashes',
        nameAr: 'الرموش',
        nameEn: 'Eyelashes',
        sortOrder: 30,
        keywordsAr: ['الرموش'],
        keywordsEn: ['Eyelashes'],
      },
      {
        id: 'cat_makeup_lips',
        slug: 'makeup-accessories-lips',
        nameAr: 'الشفاه',
        nameEn: 'Lips',
        sortOrder: 40,
        keywordsAr: ['الشفاه'],
        keywordsEn: ['Lips'],
      },
      {
        id: 'cat_makeup_nails',
        slug: 'makeup-accessories-nails',
        nameAr: 'الاظافر',
        nameEn: 'Nails',
        sortOrder: 50,
        keywordsAr: ['الاظافر'],
        keywordsEn: ['Nails'],
      },
      {
        id: 'cat_makeup_other',
        slug: 'makeup-accessories-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 60,
        keywordsAr: ['مكياج واكسسوارات أخرى'],
        keywordsEn: ['Other Makeup & Accessories'],
      },
    ],
  },

  /* ── chefaa 7. المستلزمات الطبية (Health Care Devices) ───────────────────────────── */
  {
    id: 'cat_devices',
    slug: 'health-care-devices',
    nameAr: 'المستلزمات الطبية',
    nameEn: 'Health Care Devices',
    iconName: 'heart-pulse',
    colorTheme: 'blue',
    sortOrder: 3600,
    featured: true,
    children: [
      {
        id: 'cat_devices_pain',
        slug: 'health-care-devices-pain-management',
        nameAr: 'ادارة الالم',
        nameEn: 'Pain Management',
        sortOrder: 10,
        keywordsAr: ['ادارة الالم'],
        keywordsEn: ['Pain Management'],
      },
      {
        id: 'cat_devices_respiratory',
        slug: 'health-care-devices-respiratory',
        nameAr: 'اجهزة مساعدات التنفس',
        nameEn: 'Respiratory Equipment',
        sortOrder: 20,
        keywordsAr: ['اجهزة مساعدات التنفس'],
        keywordsEn: ['Respiratory Equipment'],
      },
      {
        id: 'cat_devices_firstaid',
        slug: 'health-care-devices-first-aid',
        nameAr: 'الاسعافات الاولية',
        nameEn: 'First Aid & Disposables',
        sortOrder: 30,
        keywordsAr: ['الاسعافات الاولية'],
        keywordsEn: ['First Aid & Disposables'],
      },
      {
        id: 'cat_devices_diabetic',
        slug: 'health-care-devices-diabetic-management',
        nameAr: 'العناية بالسكري',
        nameEn: 'Diabetic Management',
        sortOrder: 40,
        keywordsAr: ['العناية بالسكري'],
        keywordsEn: ['Diabetic Management'],
      },
      {
        id: 'cat_devices_weight',
        slug: 'health-care-devices-weight-management',
        nameAr: 'ادارة الوزن',
        nameEn: 'Weight Management',
        sortOrder: 50,
        keywordsAr: ['ادارة الوزن'],
        keywordsEn: ['Weight Management'],
      },
      {
        id: 'cat_devices_incontinence',
        slug: 'health-care-devices-incontinence',
        nameAr: 'التبول اللاإرادي',
        nameEn: 'Incontinence',
        sortOrder: 60,
        keywordsAr: ['التبول اللاإرادي'],
        keywordsEn: ['Incontinence'],
      },
      {
        id: 'cat_devices_monitors',
        slug: 'health-care-devices-health-monitors',
        nameAr: 'أجهزة مراقبه الصحة',
        nameEn: 'Health Monitors',
        sortOrder: 70,
        keywordsAr: ['أجهزة مراقبه الصحة'],
        keywordsEn: ['Health Monitors'],
      },
      {
        id: 'cat_devices_other',
        slug: 'health-care-devices-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 80,
        keywordsAr: ['مستلزمات طبية أخرى'],
        keywordsEn: ['Other Health Care Devices'],
      },
    ],
  },

  /* ── chefaa 8. الفيتامينات والمكملات (Vitamins & Supplements) ────────────────────── */
  {
    id: 'cat_vitamins',
    slug: 'vitamins-supplements',
    nameAr: 'الفيتامينات والمكملات',
    nameEn: 'Vitamins & Supplements',
    iconName: 'leaf',
    colorTheme: 'green',
    sortOrder: 3700,
    featured: true,
    children: [
      {
        id: 'cat_vitamins_minerals',
        slug: 'vitamins-supplements-vitamins-minerals',
        nameAr: 'الفيتامينات والمعادن',
        nameEn: 'Vitamins & Minerals',
        sortOrder: 10,
        keywordsAr: ['الفيتامينات والمعادن'],
        keywordsEn: ['Vitamins & Minerals'],
      },
      {
        id: 'cat_vitamins_supplements',
        slug: 'vitamins-supplements-supplements',
        nameAr: 'المكملات الغذائية',
        nameEn: 'Supplements',
        sortOrder: 20,
        keywordsAr: ['المكملات الغذائية'],
        keywordsEn: ['Supplements'],
      },
      {
        id: 'cat_vitamins_slimming',
        slug: 'vitamins-supplements-slimming',
        nameAr: 'التخسيس',
        nameEn: 'Slimming',
        sortOrder: 30,
        keywordsAr: ['التخسيس'],
        keywordsEn: ['Slimming'],
      },
      {
        id: 'cat_vitamins_other',
        slug: 'vitamins-supplements-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 40,
        keywordsAr: ['فيتامينات ومكملات أخرى'],
        keywordsEn: ['Other Vitamins & Supplements'],
      },
    ],
  },

  /* ── chefaa 9. الصحة الجنسية (Sexual Wellness) ────────────────────────────────────── */
  {
    id: 'cat_sexual',
    slug: 'sexual-wellness',
    nameAr: 'الصحة الجنسية',
    nameEn: 'Sexual Wellness',
    iconName: 'heart',
    colorTheme: 'violet',
    sortOrder: 3800,
    featured: false,
    children: [
      {
        id: 'cat_sexual_condom',
        slug: 'sexual-wellness-condom',
        nameAr: 'واقي ذكري',
        nameEn: 'Condoms',
        sortOrder: 10,
        keywordsAr: ['واقي ذكري'],
        keywordsEn: ['Condoms'],
      },
      {
        id: 'cat_sexual_lubricants',
        slug: 'sexual-wellness-lubricants',
        nameAr: 'مزلقات حميمية',
        nameEn: 'Intimate Lubricants',
        sortOrder: 20,
        keywordsAr: ['مزلقات حميمية'],
        keywordsEn: ['Intimate Lubricants'],
      },
      {
        id: 'cat_sexual_pregnancy',
        slug: 'sexual-wellness-pregnancy-tests',
        nameAr: 'اختبارات الحمل',
        nameEn: 'Pregnancy Tests',
        sortOrder: 30,
        keywordsAr: ['اختبارات الحمل'],
        keywordsEn: ['Pregnancy Tests'],
      },
      {
        id: 'cat_sexual_performance',
        slug: 'sexual-wellness-performance-enhancers',
        nameAr: 'معززات الأداء',
        nameEn: 'Performance Enhancers',
        sortOrder: 40,
        keywordsAr: ['معززات الأداء'],
        keywordsEn: ['Performance Enhancers'],
      },
      {
        id: 'cat_sexual_other',
        slug: 'sexual-wellness-other',
        nameAr: 'أخرى',
        nameEn: 'Other',
        sortOrder: 50,
        keywordsAr: ['صحة جنسية أخرى'],
        keywordsEn: ['Other Sexual Wellness'],
      },
    ],
  },

  /* ── chefaa 10. مستلزمات الحيوانات (Pet Supplies) ─────────────────────────────────── */
  {
    id: 'cat_pets',
    slug: 'pet-supplies',
    nameAr: 'مستلزمات الحيوانات',
    nameEn: 'Pet Supplies',
    iconName: 'paw-print',
    colorTheme: 'orange',
    sortOrder: 3900,
    featured: false,
    children: [
      {
        id: 'cat_pets_general',
        slug: 'pet-supplies-general',
        nameAr: 'مستلزمات الحيوانات الأليفة',
        nameEn: 'Pet Supplies',
        sortOrder: 10,
        keywordsAr: ['مستلزمات الحيوانات الأليفة'],
        keywordsEn: ['Pet Supplies'],
      },
    ],
  },

  /* ── chefaa 11. Catch-all — chefaa's own "غير مصنف" bucket + anything unmapped ────
   * Roughly 0.3% of chefaa's catalog (117 of ~33.9k, live count 2026-09-24) carries no
   * level_two_category at all. Rather than drop them or guess, they land here, visibly,
   * so the review report shows exactly how many and the owner can re-classify by hand. */
  {
    id: 'cat_chefaa_other',
    slug: 'chefaa-other',
    nameAr: 'منتجات أخرى',
    nameEn: 'Other Products',
    iconName: 'package',
    colorTheme: 'brand',
    sortOrder: 4000,
    featured: false,
    children: [
      {
        id: 'cat_chefaa_other_general',
        slug: 'chefaa-other-general',
        nameAr: 'منتجات أخرى',
        nameEn: 'Other Products',
        sortOrder: 10,
        keywordsAr: ['منتجات أخرى'],
        keywordsEn: ['Other Products'],
      },
    ],
  },
];
